name: tests

on: [push, pull_request_review]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ./kickstart.sh :test
 
